/* eslint-disable */
// this is an auto-generated file
declare const styles: {
  readonly bp3MenuItem: string
  readonly bp3Active: string
  readonly bp3IntentPrimary: string
  readonly bp3Submenu: string
  readonly bp3PopoverTarget: string
  readonly bp3PopoverOpen: string
  readonly bp3Popover: string
  readonly bp3Dark: string
  readonly bp3PopoverArrow: string
  readonly bp3PopoverContent: string
  readonly bp3PopoverArrowBorder: string
  readonly bp3PopoverArrowFill: string
  readonly accordionAccordion: string
  readonly accordionPanel: string
  readonly accordionCollapse: string
  readonly accordionSummary: string
  readonly accordionLabel: string
  readonly accordionChevron: string
  readonly bp3Icon: string
  readonly accordionDetails: string
  readonly avatarAvatar: string
  readonly avatarAvatarInner: string
  readonly avatarContentStyle: string
  readonly avatarImageStyle: string
  readonly avatarHoverToolTipLayout: string
  readonly avatarHoverAvatarLayout: string
  readonly avatarAvatarPopOver: string
  readonly utilsTooltipContainer: string
  readonly styledPropsMain: string
  readonly styledPropsMarginNone: string
  readonly styledPropsMarginXsmall: string
  readonly styledPropsMarginSmall: string
  readonly styledPropsMarginMedium: string
  readonly styledPropsMarginLarge: string
  readonly styledPropsMarginXlarge: string
  readonly styledPropsMarginXxlarge: string
  readonly styledPropsMarginXxxlarge: string
  readonly styledPropsMarginHuge: string
  readonly styledPropsMarginFormSection: string
  readonly styledPropsMarginFormPanel: string
  readonly styledPropsMarginFormSubsection: string
  readonly styledPropsMarginFormPanelSubsection: string
  readonly styledPropsMarginFormActionButtons: string
  readonly styledPropsMarginTopNone: string
  readonly styledPropsMarginTopXsmall: string
  readonly styledPropsMarginTopSmall: string
  readonly styledPropsMarginTopMedium: string
  readonly styledPropsMarginTopLarge: string
  readonly styledPropsMarginTopXlarge: string
  readonly styledPropsMarginTopXxlarge: string
  readonly styledPropsMarginTopXxxlarge: string
  readonly styledPropsMarginTopHuge: string
  readonly styledPropsMarginRightNone: string
  readonly styledPropsMarginRightXsmall: string
  readonly styledPropsMarginRightSmall: string
  readonly styledPropsMarginRightMedium: string
  readonly styledPropsMarginRightLarge: string
  readonly styledPropsMarginRightXlarge: string
  readonly styledPropsMarginRightXxlarge: string
  readonly styledPropsMarginRightXxxlarge: string
  readonly styledPropsMarginRightHuge: string
  readonly styledPropsMarginBottomNone: string
  readonly styledPropsMarginBottomXsmall: string
  readonly styledPropsMarginBottomSmall: string
  readonly styledPropsMarginBottomMedium: string
  readonly styledPropsMarginBottomLarge: string
  readonly styledPropsMarginBottomXlarge: string
  readonly styledPropsMarginBottomXxlarge: string
  readonly styledPropsMarginBottomXxxlarge: string
  readonly styledPropsMarginBottomHuge: string
  readonly styledPropsMarginLeftNone: string
  readonly styledPropsMarginLeftXsmall: string
  readonly styledPropsMarginLeftSmall: string
  readonly styledPropsMarginLeftMedium: string
  readonly styledPropsMarginLeftLarge: string
  readonly styledPropsMarginLeftXlarge: string
  readonly styledPropsMarginLeftXxlarge: string
  readonly styledPropsMarginLeftXxxlarge: string
  readonly styledPropsMarginLeftHuge: string
  readonly styledPropsPaddingNone: string
  readonly styledPropsPaddingXsmall: string
  readonly styledPropsPaddingSmall: string
  readonly styledPropsPaddingMedium: string
  readonly styledPropsPaddingLarge: string
  readonly styledPropsPaddingXlarge: string
  readonly styledPropsPaddingXxlarge: string
  readonly styledPropsPaddingXxxlarge: string
  readonly styledPropsPaddingHuge: string
  readonly styledPropsPaddingDialog: string
  readonly styledPropsPaddingForm: string
  readonly styledPropsPaddingFormSection: string
  readonly styledPropsPaddingFormPanel: string
  readonly styledPropsPaddingFormSubsection: string
  readonly styledPropsPaddingTopNone: string
  readonly styledPropsPaddingTopXsmall: string
  readonly styledPropsPaddingTopSmall: string
  readonly styledPropsPaddingTopMedium: string
  readonly styledPropsPaddingTopLarge: string
  readonly styledPropsPaddingTopXlarge: string
  readonly styledPropsPaddingTopXxlarge: string
  readonly styledPropsPaddingTopXxxlarge: string
  readonly styledPropsPaddingTopHuge: string
  readonly styledPropsPaddingRightNone: string
  readonly styledPropsPaddingRightXsmall: string
  readonly styledPropsPaddingRightSmall: string
  readonly styledPropsPaddingRightMedium: string
  readonly styledPropsPaddingRightLarge: string
  readonly styledPropsPaddingRightXlarge: string
  readonly styledPropsPaddingRightXxlarge: string
  readonly styledPropsPaddingRightXxxlarge: string
  readonly styledPropsPaddingRightHuge: string
  readonly styledPropsPaddingBottomNone: string
  readonly styledPropsPaddingBottomXsmall: string
  readonly styledPropsPaddingBottomSmall: string
  readonly styledPropsPaddingBottomMedium: string
  readonly styledPropsPaddingBottomLarge: string
  readonly styledPropsPaddingBottomXlarge: string
  readonly styledPropsPaddingBottomXxlarge: string
  readonly styledPropsPaddingBottomXxxlarge: string
  readonly styledPropsPaddingBottomHuge: string
  readonly styledPropsPaddingLeftNone: string
  readonly styledPropsPaddingLeftXsmall: string
  readonly styledPropsPaddingLeftSmall: string
  readonly styledPropsPaddingLeftMedium: string
  readonly styledPropsPaddingLeftLarge: string
  readonly styledPropsPaddingLeftXlarge: string
  readonly styledPropsPaddingLeftXxlarge: string
  readonly styledPropsPaddingLeftXxxlarge: string
  readonly styledPropsPaddingLeftHuge: string
  readonly styledPropsIntentPrimary: string
  readonly styledPropsIntentSuccess: string
  readonly styledPropsIntentWarning: string
  readonly styledPropsIntentDanger: string
  readonly styledPropsFont: string
  readonly styledPropsFontH1: string
  readonly styledPropsFontH2: string
  readonly styledPropsFontH3: string
  readonly styledPropsFontH4: string
  readonly styledPropsFontH5: string
  readonly styledPropsFontH6: string
  readonly styledPropsFontSizeLarge: string
  readonly styledPropsFontLarge: string
  readonly styledPropsFontSizeMedium: string
  readonly styledPropsFontMedium: string
  readonly styledPropsFontSizeNormal: string
  readonly styledPropsFontNormal: string
  readonly styledPropsFontSizeSmall: string
  readonly styledPropsFontSmall: string
  readonly styledPropsFontSizeXsmall: string
  readonly styledPropsFontXsmall: string
  readonly styledPropsFontWeightLight: string
  readonly styledPropsFontWeightBold: string
  readonly styledPropsFontWeightSemiBold: string
  readonly styledPropsFontAlignLeft: string
  readonly styledPropsFontAlignCenter: string
  readonly styledPropsFontAlignRight: string
  readonly styledPropsFontItalic: string
  readonly styledPropsFontMono: string
  readonly styledPropsFontVariationDisplay1: string
  readonly styledPropsFontVariationDisplay2: string
  readonly styledPropsFontVariationH1: string
  readonly styledPropsFontVariationH1Semi: string
  readonly styledPropsFontVariationH2: string
  readonly styledPropsFontVariationH3: string
  readonly styledPropsFontVariationH4: string
  readonly styledPropsFontVariationH5: string
  readonly styledPropsFontVariationH6: string
  readonly styledPropsFontVariationLead: string
  readonly styledPropsFontVariationBody1: string
  readonly styledPropsFontVariationBody: string
  readonly styledPropsFontVariationBody2: string
  readonly styledPropsFontVariationBlockquote: string
  readonly styledPropsFontVariationUppercased: string
  readonly styledPropsFontVariationSmall: string
  readonly styledPropsFontVariationSmallBold: string
  readonly styledPropsFontVariationSmallSemi: string
  readonly styledPropsFontVariationTableHeaders: string
  readonly styledPropsFontVariationTiny: string
  readonly styledPropsFontVariationTinySemi: string
  readonly styledPropsFontVariationYaml: string
  readonly styledPropsFontVariationCardTitle: string
  readonly styledPropsFontVariationFormTitle: string
  readonly styledPropsFontVariationFormSubSection: string
  readonly styledPropsFontVariationFormInputText: string
  readonly styledPropsFontVariationFormLabel: string
  readonly styledPropsFontVariationFormHelp: string
  readonly styledPropsFontVariationFormMessageDanger: string
  readonly styledPropsFontVariationFormMessageWarning: string
  readonly styledPropsFontVariationFormMessageSuccess: string
  readonly styledPropsInline: string
  readonly styledPropsColor: string
  readonly styledPropsColorBlack: string
  readonly styledPropsColorWhite: string
  readonly styledPropsColorGrey1000: string
  readonly styledPropsColorGrey900: string
  readonly styledPropsColorGrey800: string
  readonly styledPropsColorGrey700: string
  readonly styledPropsColorGrey600: string
  readonly styledPropsColorGrey500: string
  readonly styledPropsColorGrey450: string
  readonly styledPropsColorGrey400: string
  readonly styledPropsColorGrey350: string
  readonly styledPropsColorGrey300: string
  readonly styledPropsColorGrey250: string
  readonly styledPropsColorGrey200: string
  readonly styledPropsColorGrey100: string
  readonly styledPropsColorGrey50: string
  readonly styledPropsColorGrey0: string
  readonly styledPropsColorBlue900: string
  readonly styledPropsColorBlue800: string
  readonly styledPropsColorBlue700: string
  readonly styledPropsColorBlue600: string
  readonly styledPropsColorBlue500: string
  readonly styledPropsColorBlue450: string
  readonly styledPropsColorBlue400: string
  readonly styledPropsColorBlue350: string
  readonly styledPropsColorBlue300: string
  readonly styledPropsColorBlue200: string
  readonly styledPropsColorBlue100: string
  readonly styledPropsColorBlue50: string
  readonly styledPropsColorRed900: string
  readonly styledPropsColorRed800: string
  readonly styledPropsColorRed700: string
  readonly styledPropsColorRed600: string
  readonly styledPropsColorRed500: string
  readonly styledPropsColorRed450: string
  readonly styledPropsColorRed400: string
  readonly styledPropsColorRed350: string
  readonly styledPropsColorRed300: string
  readonly styledPropsColorRed200: string
  readonly styledPropsColorRed100: string
  readonly styledPropsColorRed50: string
  readonly styledPropsColorYellow900: string
  readonly styledPropsColorYellow800: string
  readonly styledPropsColorYellow700: string
  readonly styledPropsColorYellow600: string
  readonly styledPropsColorYellow500: string
  readonly styledPropsColorYellow450: string
  readonly styledPropsColorYellow400: string
  readonly styledPropsColorYellow350: string
  readonly styledPropsColorYellow300: string
  readonly styledPropsColorYellow200: string
  readonly styledPropsColorYellow100: string
  readonly styledPropsColorYellow50: string
  readonly styledPropsColorGreen900: string
  readonly styledPropsColorGreen800: string
  readonly styledPropsColorGreen700: string
  readonly styledPropsColorGreen600: string
  readonly styledPropsColorGreen500: string
  readonly styledPropsColorGreen450: string
  readonly styledPropsColorGreen400: string
  readonly styledPropsColorGreen350: string
  readonly styledPropsColorGreen300: string
  readonly styledPropsColorGreen200: string
  readonly styledPropsColorGreen100: string
  readonly styledPropsColorGreen50: string
  readonly styledPropsColorPurple900: string
  readonly styledPropsColorPurple800: string
  readonly styledPropsColorPurple700: string
  readonly styledPropsColorPurple600: string
  readonly styledPropsColorPurple500: string
  readonly styledPropsColorPurple400: string
  readonly styledPropsColorPurple300: string
  readonly styledPropsColorPurple200: string
  readonly styledPropsColorPurple100: string
  readonly styledPropsColorPurple50: string
  readonly styledPropsColorSeagreen500: string
  readonly styledPropsColorMagenta900: string
  readonly styledPropsColorMagenta800: string
  readonly styledPropsColorMagenta700: string
  readonly styledPropsColorMagenta600: string
  readonly styledPropsColorMagenta500: string
  readonly styledPropsColorMagenta400: string
  readonly styledPropsColorMagenta300: string
  readonly styledPropsColorMagenta200: string
  readonly styledPropsColorMagenta100: string
  readonly styledPropsColorMagenta50: string
  readonly styledPropsColorAqua500: string
  readonly styledPropsColorDark600: string
  readonly styledPropsColorDark500: string
  readonly styledPropsColorDark400: string
  readonly styledPropsColorDark300: string
  readonly styledPropsColorDark200: string
  readonly styledPropsColorLight600: string
  readonly styledPropsColorLight500: string
  readonly styledPropsColorLight400: string
  readonly styledPropsColorLight300: string
  readonly styledPropsColorLight200: string
  readonly styledPropsColorBlack100: string
  readonly styledPropsColorPrimary1: string
  readonly styledPropsColorPrimary2: string
  readonly styledPropsColorPrimary3: string
  readonly styledPropsColorPrimary4: string
  readonly styledPropsColorPrimary5: string
  readonly styledPropsColorPrimary6: string
  readonly styledPropsColorPrimary7: string
  readonly styledPropsColorPrimary8: string
  readonly styledPropsColorPrimary9: string
  readonly styledPropsColorPrimary10: string
  readonly styledPropsColorPrimaryBg: string
  readonly styledPropsColorOrange900: string
  readonly styledPropsColorOrange800: string
  readonly styledPropsColorOrange700: string
  readonly styledPropsColorOrange600: string
  readonly styledPropsColorOrange500: string
  readonly styledPropsColorOrange400: string
  readonly styledPropsColorOrange300: string
  readonly styledPropsColorOrange200: string
  readonly styledPropsColorOrange100: string
  readonly styledPropsColorOrange50: string
  readonly styledPropsColorTeal900: string
  readonly styledPropsColorTeal800: string
  readonly styledPropsColorTeal700: string
  readonly styledPropsColorTeal600: string
  readonly styledPropsColorTeal500: string
  readonly styledPropsColorTeal400: string
  readonly styledPropsColorTeal300: string
  readonly styledPropsColorTeal200: string
  readonly styledPropsColorTeal100: string
  readonly styledPropsColorTeal50: string
  readonly styledPropsColorLime900: string
  readonly styledPropsColorLime800: string
  readonly styledPropsColorLime700: string
  readonly styledPropsColorLime600: string
  readonly styledPropsColorLime500: string
  readonly styledPropsColorLime400: string
  readonly styledPropsColorLime300: string
  readonly styledPropsColorLime200: string
  readonly styledPropsColorLime100: string
  readonly styledPropsColorLime50: string
  readonly styledPropsColorError: string
  readonly styledPropsColorWarning: string
  readonly styledPropsColorSuccess: string
  readonly styledPropsBackgroundBlack: string
  readonly styledPropsBackgroundWhite: string
  readonly styledPropsBackgroundGrey900: string
  readonly styledPropsBackgroundGrey800: string
  readonly styledPropsBackgroundGrey700: string
  readonly styledPropsBackgroundGrey600: string
  readonly styledPropsBackgroundGrey500: string
  readonly styledPropsBackgroundGrey450: string
  readonly styledPropsBackgroundGrey400: string
  readonly styledPropsBackgroundGrey350: string
  readonly styledPropsBackgroundGrey300: string
  readonly styledPropsBackgroundGrey250: string
  readonly styledPropsBackgroundGrey200: string
  readonly styledPropsBackgroundGrey100: string
  readonly styledPropsBackgroundBlue800: string
  readonly styledPropsBackgroundBlue700: string
  readonly styledPropsBackgroundBlue600: string
  readonly styledPropsBackgroundBlue500: string
  readonly styledPropsBackgroundBlue450: string
  readonly styledPropsBackgroundBlue400: string
  readonly styledPropsBackgroundBlue350: string
  readonly styledPropsBackgroundBlue300: string
  readonly styledPropsBackgroundBlue200: string
  readonly styledPropsBackgroundBlue100: string
  readonly styledPropsBackgroundBlue50: string
  readonly styledPropsBackgroundRed800: string
  readonly styledPropsBackgroundRed700: string
  readonly styledPropsBackgroundRed600: string
  readonly styledPropsBackgroundRed500: string
  readonly styledPropsBackgroundRed450: string
  readonly styledPropsBackgroundRed400: string
  readonly styledPropsBackgroundRed350: string
  readonly styledPropsBackgroundRed300: string
  readonly styledPropsBackgroundRed200: string
  readonly styledPropsBackgroundRed100: string
  readonly styledPropsBackgroundYellow800: string
  readonly styledPropsBackgroundYellow700: string
  readonly styledPropsBackgroundYellow600: string
  readonly styledPropsBackgroundYellow500: string
  readonly styledPropsBackgroundYellow450: string
  readonly styledPropsBackgroundYellow400: string
  readonly styledPropsBackgroundYellow350: string
  readonly styledPropsBackgroundYellow300: string
  readonly styledPropsBackgroundYellow200: string
  readonly styledPropsBackgroundYellow100: string
  readonly styledPropsBackgroundGreen800: string
  readonly styledPropsBackgroundGreen700: string
  readonly styledPropsBackgroundGreen600: string
  readonly styledPropsBackgroundGreen500: string
  readonly styledPropsBackgroundGreen450: string
  readonly styledPropsBackgroundGreen400: string
  readonly styledPropsBackgroundGreen350: string
  readonly styledPropsBackgroundGreen300: string
  readonly styledPropsBackgroundGreen200: string
  readonly styledPropsBackgroundGreen100: string
  readonly styledPropsBackgroundPurple900: string
  readonly styledPropsBackgroundPurple600: string
  readonly styledPropsBackgroundPurple500: string
  readonly styledPropsBackgroundPurple400: string
  readonly styledPropsBackgroundPurple300: string
  readonly styledPropsBackgroundPurple200: string
  readonly styledPropsBackgroundPurple100: string
  readonly styledPropsBackgroundSeagreen500: string
  readonly styledPropsBackgroundOrange600: string
  readonly styledPropsBackgroundOrange500: string
  readonly styledPropsBackgroundOrange400: string
  readonly styledPropsBackgroundOrange300: string
  readonly styledPropsBackgroundOrange200: string
  readonly styledPropsBackgroundMagenta500: string
  readonly styledPropsBackgroundAqua500: string
  readonly styledPropsBackgroundDark600: string
  readonly styledPropsBackgroundDark500: string
  readonly styledPropsBackgroundDark400: string
  readonly styledPropsBackgroundDark300: string
  readonly styledPropsBackgroundDark200: string
  readonly styledPropsBackgroundLight600: string
  readonly styledPropsBackgroundLight500: string
  readonly styledPropsBackgroundLight400: string
  readonly styledPropsBackgroundLight300: string
  readonly styledPropsBackgroundLight200: string
  readonly styledPropsBackgroundTeal500: string
  readonly styledPropsBackgroundTeal400: string
  readonly styledPropsBackgroundTeal300: string
  readonly styledPropsBackgroundTeal200: string
  readonly styledPropsBackgroundBlack100: string
  readonly styledPropsBackgroundBlue900: string
  readonly styledPropsBackgroundPrimary1: string
  readonly styledPropsBackgroundPrimary2: string
  readonly styledPropsBackgroundPrimary3: string
  readonly styledPropsBackgroundPrimary4: string
  readonly styledPropsBackgroundPrimary5: string
  readonly styledPropsBackgroundPrimary6: string
  readonly styledPropsBackgroundPrimary7: string
  readonly styledPropsBackgroundPrimary8: string
  readonly styledPropsBackgroundPrimary9: string
  readonly styledPropsBackgroundPrimary10: string
  readonly styledPropsBackgroundPrimaryBg: string
  readonly styledPropsBackgroundForm: string
  readonly styledPropsBackgroundFormSection: string
  readonly styledPropsBackgroundFormPanel: string
  readonly styledPropsBackgroundFormSubsection: string
  readonly styledPropsBorder: string
  readonly styledPropsBorderFalse: string
  readonly styledPropsBorderTop: string
  readonly styledPropsBorderRight: string
  readonly styledPropsBorderBottom: string
  readonly styledPropsBorderLeft: string
  readonly styledPropsBorderColorBlack: string
  readonly styledPropsBorderColorWhite: string
  readonly styledPropsBorderColorGrey900: string
  readonly styledPropsBorderColorGrey800: string
  readonly styledPropsBorderColorGrey700: string
  readonly styledPropsBorderColorGrey600: string
  readonly styledPropsBorderColorGrey500: string
  readonly styledPropsBorderColorGrey450: string
  readonly styledPropsBorderColorGrey400: string
  readonly styledPropsBorderColorGrey350: string
  readonly styledPropsBorderColorGrey300: string
  readonly styledPropsBorderColorGrey200: string
  readonly styledPropsBorderColorGrey100: string
  readonly styledPropsBorderColorBlue800: string
  readonly styledPropsBorderColorBlue700: string
  readonly styledPropsBorderColorBlue600: string
  readonly styledPropsBorderColorBlue500: string
  readonly styledPropsBorderColorBlue450: string
  readonly styledPropsBorderColorBlue400: string
  readonly styledPropsBorderColorBlue350: string
  readonly styledPropsBorderColorBlue300: string
  readonly styledPropsBorderColorBlue200: string
  readonly styledPropsBorderColorBlue100: string
  readonly styledPropsBorderColorBlue50: string
  readonly styledPropsBorderColorRed800: string
  readonly styledPropsBorderColorRed700: string
  readonly styledPropsBorderColorRed600: string
  readonly styledPropsBorderColorRed500: string
  readonly styledPropsBorderColorRed450: string
  readonly styledPropsBorderColorRed400: string
  readonly styledPropsBorderColorRed350: string
  readonly styledPropsBorderColorRed300: string
  readonly styledPropsBorderColorRed200: string
  readonly styledPropsBorderColorRed100: string
  readonly styledPropsBorderColorYellow800: string
  readonly styledPropsBorderColorYellow700: string
  readonly styledPropsBorderColorYellow600: string
  readonly styledPropsBorderColorYellow500: string
  readonly styledPropsBorderColorYellow450: string
  readonly styledPropsBorderColorYellow400: string
  readonly styledPropsBorderColorYellow350: string
  readonly styledPropsBorderColorYellow300: string
  readonly styledPropsBorderColorYellow200: string
  readonly styledPropsBorderColorYellow100: string
  readonly styledPropsBorderColorGreen800: string
  readonly styledPropsBorderColorGreen700: string
  readonly styledPropsBorderColorGreen600: string
  readonly styledPropsBorderColorGreen500: string
  readonly styledPropsBorderColorGreen450: string
  readonly styledPropsBorderColorGreen400: string
  readonly styledPropsBorderColorGreen350: string
  readonly styledPropsBorderColorGreen300: string
  readonly styledPropsBorderColorGreen200: string
  readonly styledPropsBorderColorGreen100: string
  readonly styledPropsBorderColorPurple900: string
  readonly styledPropsBorderColorPurple500: string
  readonly styledPropsBorderColorPurple100: string
  readonly styledPropsBorderColorSeagreen500: string
  readonly styledPropsBorderColorOrange500: string
  readonly styledPropsBorderColorMagenta500: string
  readonly styledPropsBorderColorDark: string
  readonly styledPropsBorderColorLight: string
  readonly styledPropsBorderColorRed: string
  readonly styledPropsBorderColorGreen: string
  readonly styledPropsBorderColorBlue: string
  readonly styledPropsBorderColorYellow: string
  readonly styledPropsBorderColorOrange: string
  readonly styledPropsBorderColorTeal: string
  readonly styledPropsBorderColorPurple: string
  readonly styledPropsFlex: string
  readonly styledPropsFlexInline: string
  readonly styledPropsFlexAlignCenterCenter: string
  readonly styledPropsFlexDistributionSpaceBetween: string
  readonly styledPropsFlexAlignItemsStretch: string
  readonly styledPropsFlexAlignItemsCenter: string
  readonly styledPropsFlexAlignItemsEnd: string
  readonly styledPropsFlexAlignItemsStart: string
  readonly styledPropsFlexAlignItemsFlexStart: string
  readonly styledPropsFlexAlignItemsFlexEnd: string
  readonly styledPropsFlexAlignItemsBaseline: string
  readonly styledPropsFlexAlignItemsSelfStart: string
  readonly styledPropsFlexAlignItemsSelfEnd: string
  readonly styledPropsFlexJustifyContentFlexStart: string
  readonly styledPropsFlexJustifyContentFlexEnd: string
  readonly styledPropsFlexJustifyContentCenter: string
  readonly styledPropsFlexJustifyContentSpaceBetween: string
  readonly styledPropsFlexJustifyContentSpaceAround: string
  readonly styledPropsFlexJustifyContentSpaceEvenly: string
  readonly styledPropsFlexJustifyContentStart: string
  readonly styledPropsFlexJustifyContentEnd: string
  readonly styledPropsFlexJustifyContentLeft: string
  readonly styledPropsFlexJustifyContentRight: string
  readonly layoutVertical: string
  readonly layoutHorizontal: string
  readonly layoutLayoutSpacingXsmall: string
  readonly layoutLayoutSpacingSmall: string
  readonly layoutLayoutSpacingMedium: string
  readonly layoutLayoutSpacingLarge: string
  readonly layoutLayoutSpacingXlarge: string
  readonly layoutLayoutSpacingXxlarge: string
  readonly layoutLayoutSpacingXxxlarge: string
  readonly layoutLayoutSpacingHuge: string
  readonly textLineclamp: string
  readonly textWithDocsTooltip: string
  readonly tooltipAcenter: string
  readonly bp3PopoverWrapper: string
  readonly tooltipTooltipIcon: string
  readonly tooltipTooltipWrapper: string
  readonly tooltipTooltipContentWrapper: string
  readonly avatarGroupStack: string
  readonly avatarGroupNoStack: string
  readonly avatarGroupStackAvatar: string
  readonly buttonButton: string
  readonly buttonVariation: string
  readonly buttonWithLeftIcon: string
  readonly buttonWithRightIcon: string
  readonly buttonVariationLink: string
  readonly buttonVariationPrimary: string
  readonly buttonVariationSecondary: string
  readonly buttonVariationTertiary: string
  readonly buttonVariationIcon: string
  readonly buttonSize: string
  readonly buttonLarge: string
  readonly buttonSmall: string
  readonly buttonWithoutShadow: string
  readonly buttonIconOnly: string
  readonly buttonRound: string
  readonly buttonLink: string
  readonly buttonWithCurrentColor: string
  readonly bp3Spinner: string
  readonly bp3SpinnerHead: string
  readonly buttonWithDocsTooltip: string
  readonly bp3FocusDisabled: string
  readonly buttonGroupBtnGroup: string
  readonly checkboxCheckbox: string
  readonly bp3ControlIndicator: string
  readonly dialogDialog: string
  readonly dialogChildren: string
  readonly dialogClose: string
  readonly bp3DialogHeader: string
  readonly bp3Heading: string
  readonly bp3DialogCloseButton: string
  readonly toggleToggle: string
  readonly toggleToggleIcon: string
  readonly toggleInput: string
  readonly listList: string
  readonly listItemItem: string
  readonly tagMain: string
  readonly bp3Tag: string
  readonly bp3IntentSuccess: string
  readonly bp3IntentWarning: string
  readonly bp3IntentDanger: string
  readonly bp3Minimal: string
  readonly radioRadio: string
  readonly radioRadioGroup: string
  readonly radioButtonRadio: string
  readonly radioButtonRadioGroup: string
  readonly bp3Radio: string
  readonly radioButtonInline: string
  readonly switchSwitch: string
  readonly switchIconSwitchIcon: string
  readonly switchIconDisabled: string
  readonly switchIconLabelClass: string
  readonly switchIconIcon: string
  readonly switchIconToggleSwitch: string
  readonly switchIconToggleContent: string
  readonly labelMain: string
  readonly carouselCarousel: string
  readonly carouselCarouselView: string
  readonly carouselCarouselLeft: string
  readonly carouselCarouselRight: string
  readonly carouselCarouselItem: string
  readonly carouselActive: string
  readonly carouselCarouselItemPrev: string
  readonly carouselCarouselItemNext: string
  readonly carouselCarouselIndicators: string
  readonly carouselIndicator: string
  readonly tabsMain: string
  readonly bp3Tabs: string
  readonly bp3Tab: string
  readonly tabsIcons: string
  readonly bp3TabList: string
  readonly tabsHorizontal: string
  readonly bp3TabIndicatorWrapper: string
  readonly bp3TabIndicator: string
  readonly tabsVertical: string
  readonly textInputMain: string
  readonly bp3Input: string
  readonly textInputHasError: string
  readonly textInputErrorIcon: string
  readonly textInputSuccess: string
  readonly bp3InputAction: string
  readonly bp3InputGroup: string
  readonly formErrorErrorDiv: string
  readonly formErrorError: string
  readonly formErrorErrorIcon: string
  readonly formErrorErrorTextIcon: string
  readonly fieldArrayContainer: string
  readonly fieldArrayTitle: string
  readonly fieldArrayText: string
  readonly fieldArrayNoData: string
  readonly fieldArrayDeleteColumn: string
  readonly durationInputMain: string
  readonly durationInputHelpIcon: string
  readonly durationInputWarnIcon: string
  readonly selectMain: string
  readonly bp3InputLeftContainer: string
  readonly bp3Large: string
  readonly bp3Overlay: string
  readonly bp3TransitionContainer: string
  readonly bp3Menu: string
  readonly selectMenuItem: string
  readonly selectMenuItemLabel: string
  readonly selectActive: string
  readonly selectMenuItemSizeSmall: string
  readonly selectMenuItemSizeLarge: string
  readonly selectDisabled: string
  readonly selectLoading: string
  readonly iconContainer: string
  readonly selectV2Main: string
  readonly selectV2MenuItem: string
  readonly selectV2Active: string
  readonly selectV2MenuItemSizeSmall: string
  readonly selectV2MenuItemSizeLarge: string
  readonly selectV2Disabled: string
  readonly selectV2Loading: string
  readonly dropDownMain: string
  readonly dropDownDisabled: string
  readonly dropDownDropdownButton: string
  readonly dropDownWithBorder: string
  readonly dropDownLabelWrapper: string
  readonly dropDownLabel: string
  readonly dropDownMinWidth: string
  readonly dropDownSelected: string
  readonly dropDownBtnWrapper: string
  readonly bp3Button: string
  readonly dropDownPopover: string
  readonly dropDownMenuItem: string
  readonly dropDownActive: string
  readonly stepWizardMain: string
  readonly stepWizardNavBar: string
  readonly stepWizardNavBarList: string
  readonly stepWizardNavStep: string
  readonly stepWizardActiveStep: string
  readonly stepWizardStepName: string
  readonly stepWizardNumber: string
  readonly stepWizardCompletedStep: string
  readonly stepWizardNestedStep: string
  readonly stepWizardStepDetails: string
  readonly stepWizardHeader: string
  readonly stepWizardTitle: string
  readonly stepWizardCompletedIcon: string
  readonly stepWizardHarnessWatermark: string
  readonly multiSelectMain: string
  readonly multiSelectTag: string
  readonly bp3TagRemove: string
  readonly bp3IconSmallCross: string
  readonly multiSelectMenuItem: string
  readonly multiSelectMenuItemLabel: string
  readonly multiSelectCheckbox: string
  readonly multiSelectActive: string
  readonly multiSelectDisabled: string
  readonly multiSelectLoading: string
  readonly modalRendererModal: string
  readonly modalRendererInnerContainer: string
  readonly modalRendererTitle: string
  readonly modalRendererDraggable: string
  readonly modalRendererContent: string
  readonly tabNavigationContainer: string
  readonly tabNavigationTags: string
  readonly tabNavigationSmall: string
  readonly tabNavigationActive: string
  readonly tabNavigationDisabled: string
  readonly thumbnailSquareCardContainer: string
  readonly thumbnailSquareCard: string
  readonly thumbnailLabel: string
  readonly thumbnailBigger: string
  readonly cardCard: string
  readonly cardInteractive: string
  readonly cardCardIcon: string
  readonly cardSelected: string
  readonly cardDisabled: string
  readonly cardCardMenu: string
  readonly cardColorIdentifier: string
  readonly cardTitle: string
  readonly cardDots: string
  readonly cardMenu: string
  readonly cardCorner: string
  readonly cardBadge: string
  readonly thumbnailSelectMainContainer: string
  readonly bp3FormHelperText: string
  readonly thumbnailSelectChangeButton: string
  readonly groupedThumbnailSelectMainContainer: string
  readonly groupedThumbnailSelectContainer: string
  readonly groupedThumbnailSelectThumbnailsRow: string
  readonly groupedThumbnailSelectChangeButton: string
  readonly dateInputDateInput: string
  readonly dateInputCalendarIcon: string
  readonly dateInputHelpText: string
  readonly dateInputHelpIcon: string
  readonly paginationContainer: string
  readonly paginationText: string
  readonly expandingSearchInputMain: string
  readonly expandingSearchInputFlip: string
  readonly expandingSearchInputAlwaysExpanded: string
  readonly expandingSearchInputLight: string
  readonly expandingSearchInputFilter: string
  readonly expandingSearchInputFind: string
  readonly expandingSearchInputDark: string
  readonly expandingSearchInputNotransition: string
  readonly expandingSearchInputIcon: string
  readonly expandingSearchInputBtnWrapper: string
  readonly tagInputPopover: string
  readonly tagInputTagInput: string
  readonly tagInputSpinner: string
  readonly tagInputInput: string
  readonly tagInputReadonly: string
  readonly tagInputTag: string
  readonly tagInputAddTagButton: string
  readonly codeBlockCodeBlock: string
  readonly multiLevelSelectMultiLevelSelectorContainer: string
  readonly multiLevelSelectLabel: string
  readonly multiLevelSelectMenuClose: string
  readonly multiLevelSelectMenuOpen: string
  readonly multiLevelSelectActive: string
  readonly multiLevelSelectInactive: string
  readonly multiLevelSelectMultiSelectorContainer: string
  readonly multiLevelSelectMultiSelector: string
  readonly multiLevelSelectMultiSelectorPlaceholder: string
  readonly multiLevelSelectOptionsSelectedContainer: string
  readonly multiLevelSelectOptionsValue: string
  readonly multiLevelSelectOptionsGroup: string
  readonly multiLevelSelectMultiSelectorButton: string
  readonly multiLevelSelectArrowDown: string
  readonly multiLevelSelectArrowUp: string
  readonly multiLevelSelectMultiLevelOptionsContainer: string
  readonly multiLevelSelectOptionsMainMenu: string
  readonly multiLevelSelectOptionsSubMenu: string
  readonly multiLevelSelectOptionsContainer: string
  readonly multiLevelSelectOptionsLabel: string
  readonly multiLevelSelectOptionsSubMenuContainer: string
  readonly multiLevelSelectOptionsSubMenuHeader: string
  readonly multiLevelSelectArrowRight: string
  readonly stackTraceListMain: string
  readonly stackTraceListListContainer: string
  readonly stackTraceListPanel: string
  readonly stackTraceListTextContainer: string
  readonly stackTraceListTimestamp: string
  readonly stackTraceListTextContent: string
  readonly stackTraceListIsExpandible: string
  readonly stackTraceListCollapseButtonText: string
  readonly collapseMain: string
  readonly collapseHeader: string
  readonly collapseCollapse: string
  readonly collapseHeaderMain: string
  readonly collapseHeaderLeftSection: string
  readonly collapseHeaderTitle: string
  readonly collapseListPanelMain: string
  readonly collapseListPanelCollapse: string
  readonly collapseListPanelFooterContent: string
  readonly graphErrorMain: string
  readonly graphErrorImg: string
  readonly graphErrorTitle: string
  readonly graphErrorSecondLink: string
  readonly selectWithSubviewRemoveDropdownStyling: string
  readonly sparkChartMain: string
  readonly container: string
  readonly vertical: string
  readonly progressBar: string
  readonly progressTrack: string
  readonly progressFill: string
  readonly bp3Portal: string
  readonly bp3Dialog: string
  readonly formikFormMain: string
  readonly bp3FormGroup: string
  readonly bp3FileUploadInput: string
  readonly colorPickerPicker: string
  readonly bp3Label: string
  readonly bp3TagInput: string
  readonly bp3Disabled: string
  readonly bp3TagInputValues: string
  readonly bp3FileInput: string
  readonly bp3InputGhost: string
  readonly formikFormCheckBoxDocTooltipLabel: string
  readonly formikFormInlineRadioGroup: string
  readonly overlaySpinnerOverlaySpinner: string
  readonly overlaySpinnerOverlay: string
  readonly colorPickerColor: string
  readonly colorPickerTransparent: string
  readonly colorPickerGrid: string
  readonly colorPickerSelected: string
  readonly inputWithIdentifierTxtNameContainer: string
  readonly inputWithIdentifierTxtIdContainer: string
  readonly inputWithIdentifierIdValue: string
  readonly multiTypeInputInput: string
  readonly multiTypeInputMini: string
  readonly multiTypeInputBp3IntentPrimary: string
  readonly multiTypeInputBp3IntentSuccess: string
  readonly multiTypeInputBp3IntentWarning: string
  readonly multiTypeInputBp3IntentDanger: string
  readonly multiTypeInputDisabled: string
  readonly multiTypeInputBtn: string
  readonly multiTypeInputMain: string
  readonly multiTypeInputWrapper: string
  readonly multiTypeInputMiniBtn: string
  readonly multiTypeInputFixed: string
  readonly multiTypeInputRuntime: string
  readonly multiTypeInputExpression: string
  readonly multiTypeInputInputTypeButtonPopoverClass: string
  readonly multiTypeInputMenu: string
  readonly multiTypeInputMenuItem: string
  readonly multiTypeInputMenuItemLabel: string
  readonly multiTypeInputPopover: string
  readonly multiTypeInputSelect: string
  readonly multiTypeInputFixedValueInput: string
  readonly expressionInputMenu: string
  readonly expressionInputMenuItem: string
  readonly expressionInputGroup1: string
  readonly expressionInputGroup2: string
  readonly expressionInputPopover: string
  readonly categorizedSelectCategoryItem: string
  readonly categorizedSelectCollapseIcon: string
  readonly categorizedSelectItem: string
  readonly categorizedSelectCreatableOption: string
  readonly categorizedSelectAddNewOptionForm: string
  readonly stepsProgressStepsProgress: string
  readonly stepsProgressProgressBar: string
  readonly stepsProgressProgressHeight: string
  readonly stepsProgressStepWrap: string
  readonly weightedStackMain: string
  readonly weightedStackStack: string
  readonly weightedStackStackLabelCommon: string
  readonly weightedStackStackColumn: string
  readonly weightedStackStackLabel: string
  readonly weightedStackStackColumnReverse: string
  readonly weightedStackStackRow: string
  readonly weightedStackStackRowReverse: string
  readonly breadcrumbsBreadcrumbs: string
  readonly breadcrumbsBreadcrumb: string
  readonly gridListToggleGridUnselected: string
  readonly gridListToggleListUnselected: string
  readonly gridListToggleGridButton: string
  readonly gridListToggleListButton: string
  readonly reactRoot: string
  readonly spinnerRotation: string
}
export default styles
